[package]
name = "syrusakbary/cowsay"
version = "0.3.0"
description = "cowsay is a program that generates ASCII pictures of a cow with a message"
readme = "README.md"
repository = "https://github.com/wapm-packages/cowsay"
entrypoint = "cowsay"

[[module]]
name = "cowsay"
source = "target/wasm32-wasip1/release/cowsay.wasm"
abi = "wasi"
interfaces = {wasi= "0.1.0-unstable"}

[[command]]
name = "cowsay"
module = "cowsay"

[[command]]
name = "cowthink"
module = "cowsay"
